### ISSUE TITLE
[BUG] Stealing Cop cars from Actual Cops

### ISSUE THREAD

**Issue by xH0RIZ0Nx** [lastnexusdev/GTA-Athena#9]
**Describe the bug**
No Way to lock "personal" Police or EMS cars. This has resulted in more police cars being taken and left around the map. (momo)

**To Reproduce**
Step1: Respond to 911 call has cop or ems
Step2:  chase Kevin
Step3: Return with cuffed Kevin to car
Step4: Watch Momo drive away in your police/EMS car or helicopter

**Screenshots / Videos**
See for yourself

**Additional context**
You have 65% chance of momo jacking yo shit

**Comment by jhina5422** [comment]
Confirmed that no locking script currently exists.

**Comment by lastnexusdev** [comment]
Fixed with the implementation of the key system

**Comment by xH0RIZ0Nx** [comment]
Still Happening. Momo stole police truck after messing it up with a backhoe and drove it around on no tires. no way to actually get keys without BUYING a car. also now Don stillwill still has all of artyoms keys

**Comment by jhina5422** [comment]
reopening for developer review.

**Comment by lastnexusdev** [comment]
Cars need to be locked for personal cars a player will always be able to take a car in motion so she could still steal the cars that way but those should only be stock cars not the new ones
